name: Render React App Deploy

on:
  push:
    branches:
      - Nicolas-Granatelli-patch-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: "https://api.render.com/deploy/srv-cl5h2m472pts73em0gsg?key=heCDV9InmtA"
